version: '3'
services: 
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - "vialapi:vialapi"
    command: "/etc/nginx/run_nginx.sh"
    env_file: .env
    networks:
      - net3

  vialapi:
    restart: always
    build: ./vial
    ports:
      - "8002:8002"
    links:
      - "timescaledb:timescaledb"
    volumes:
      - "./wallet_1.json:/usr/local/aqua-vial/wallet_1.json"
    env_file: .env
    command: "node bin/aqua-vial.js --log-level=debug --markets-json=markets.json --tokens-json=tokens.json --service-mode=api --port=8002"
    networks:
      - net3

  vialrpc:
    restart: always
    build: ./vial
    links:
      - "timescaledb:timescaledb"
    volumes:
      - "./wallet_1.json:/usr/local/aqua-vial/wallet_1.json"
    env_file: .env
    command: "node bin/aqua-vial.js --log-level=debug --markets-json=markets.json --tokens-json=tokens.json --service-mode=rpc --port=8001"
    networks:
      - net3

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: always
#    expose:
#      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - "tsdata:/var/lib/postgresql/data"
    env_file: .env
    networks:
      - net3

volumes:
  tsdata:

networks:
  net3:
    external: true

