version: '3'
services: 
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "9443:9443"
    links:
      - "vial:vial"
    command: "/etc/nginx/run_nginx.sh"
    env_file: .env
    networks:
      - net3

  vial:
    restart: always
    build: ./vial
    expose:
      - "8000"
    links:
      - "timescaledb:timescaledb"
    volumes:
      - "./wallet_1.json:/usr/local/aqua-vial/wallet_1.json"
    env_file: .env
    networks:
      - net3

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    expose:
      - "5432"
    volumes:
      - "tsdata:/home/postgres/pgdata/data"
    env_file: .env
    networks:
      - net3

volumes:
  tsdata:

networks:
  net3:
    external: true

