version: '3'
services: 
  web:
    restart: always
    build: ./web
    ports:
      - "9443:9443"
    #volumes:
    #  - "./web/nuxt-app:/usr/src/nuxt-app"
    entrypoint: npm run dev
    networks:
      - net3

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "tsdata:/home/postgres/pgdata/data"
    env_file: .env
    networks:
      - net3

volumes:
  tsdata:

networks:
  net3:
    external: true

