version: '3'
services: 
  web:
    restart: always
    build: ./web
    ports:
      - "9443:9443"
    #volumes:
    #  - "./web/nuxt-app:/usr/src/nuxt-app"
    entrypoint: npm run dev
    networks:
      - net3

networks:
  net3:
    external: true

